In [3]:
from google.colab import drive
drive.mount('/content/gdrive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive/

In [0]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
np.random.seed=1994

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
pd.set_option('display.max_rows', 500)

# pd.set_option('display.max_columns', 500)
# pd.set_option('display.width', 1000)

In [0]:

train=pd.read_csv('/content/gdrive/My Drive/Competetion_ML/Zindi/Train.csv')
test=pd.read_csv('/content/gdrive/My Drive/Competetion_ML/Zindi/Test.csv')
s=pd.read_csv('/content/gdrive/My Drive/Competetion_ML/Zindi/SampleSubmission (1).csv')

In [56]:
train[train.columns[train.columns.str.startswith('L3')]].columns

Index(['L3_NO2_NO2_column_number_density',
       'L3_NO2_NO2_slant_column_number_density',
       'L3_NO2_absorbing_aerosol_index', 'L3_NO2_cloud_fraction',
       'L3_NO2_sensor_altitude', 'L3_NO2_sensor_azimuth_angle',
       'L3_NO2_sensor_zenith_angle', 'L3_NO2_solar_azimuth_angle',
       'L3_NO2_solar_zenith_angle',
       'L3_NO2_stratospheric_NO2_column_number_density',
       'L3_NO2_tropopause_pressure',
       'L3_NO2_tropospheric_NO2_column_number_density',
       'L3_O3_O3_column_number_density', 'L3_O3_O3_effective_temperature',
       'L3_O3_cloud_fraction', 'L3_O3_sensor_azimuth_angle',
       'L3_O3_sensor_zenith_angle', 'L3_O3_solar_azimuth_angle',
       'L3_O3_solar_zenith_angle', 'L3_CO_CO_column_number_density',
       'L3_CO_H2O_column_number_density', 'L3_CO_cloud_height',
       'L3_CO_sensor_altitude', 'L3_CO_sensor_azimuth_angle',
       'L3_CO_sensor_zenith_angle', 'L3_CO_solar_azimuth_angle',
       'L3_CO_solar_zenith_angle', 'L3_HCHO_HCHO_slant_column_number_density',
       'L3_HCHO_cloud_fraction', 'L3_HCHO_sensor_azimuth_angle',
       'L3_HCHO_sensor_zenith_angle', 'L3_HCHO_solar_azimuth_angle',
       'L3_HCHO_solar_zenith_angle',
       'L3_HCHO_tropospheric_HCHO_column_number_density',
       'L3_HCHO_tropospheric_HCHO_column_number_density_amf',
       'L3_CLOUD_cloud_base_height', 'L3_CLOUD_cloud_base_pressure',
       'L3_CLOUD_cloud_fraction', 'L3_CLOUD_cloud_optical_depth',
       'L3_CLOUD_cloud_top_height', 'L3_CLOUD_cloud_top_pressure',
       'L3_CLOUD_sensor_azimuth_angle', 'L3_CLOUD_sensor_zenith_angle',
       'L3_CLOUD_solar_azimuth_angle', 'L3_CLOUD_solar_zenith_angle',
       'L3_CLOUD_surface_albedo', 'L3_AER_AI_absorbing_aerosol_index',
       'L3_AER_AI_sensor_altitude', 'L3_AER_AI_sensor_azimuth_angle',
       'L3_AER_AI_sensor_zenith_angle', 'L3_AER_AI_solar_azimuth_angle',
       'L3_AER_AI_solar_zenith_angle', 'L3_SO2_SO2_column_number_density',
       'L3_SO2_SO2_column_number_density_amf',
       'L3_SO2_SO2_slant_column_number_density',
       'L3_SO2_absorbing_aerosol_index', 'L3_SO2_cloud_fraction',
       'L3_SO2_sensor_azimuth_angle', 'L3_SO2_sensor_zenith_angle',
       'L3_SO2_solar_azimuth_angle', 'L3_SO2_solar_zenith_angle',
       'L3_CH4_CH4_column_volume_mixing_ratio_dry_air',
       'L3_CH4_aerosol_height', 'L3_CH4_aerosol_optical_depth',
       'L3_CH4_sensor_azimuth_angle', 'L3_CH4_sensor_zenith_angle',
       'L3_CH4_solar_azimuth_angle', 'L3_CH4_solar_zenith_angle'],
      dtype='object')

In [57]:
train.head()

        Place_ID X Date  ... L3_CH4_solar_zenith_angle
0  010Q650 X 2020-01-02  ...                 22.545118
1  010Q650 X 2020-01-03  ...                 19.293652
2  010Q650 X 2020-01-04  ...                       NaN
3  010Q650 X 2020-01-05  ...                       NaN
4  010Q650 X 2020-01-06  ...                       NaN

[5 rows x 82 columns]

In [58]:
test.isnull().sum()

Place_ID X Date                                            0
Date                                                       0
Place_ID                                                   0
precipitable_water_entire_atmosphere                       0
relative_humidity_2m_above_ground                          0
specific_humidity_2m_above_ground                          0
temperature_2m_above_ground                                0
u_component_of_wind_10m_above_ground                       0
v_component_of_wind_10m_above_ground                       0
L3_NO2_NO2_column_number_density                        1327
L3_NO2_NO2_slant_column_number_density                  1327
L3_NO2_absorbing_aerosol_index                          1327
L3_NO2_cloud_fraction                                   1327
L3_NO2_sensor_altitude                                  1327
L3_NO2_sensor_azimuth_angle                             1327
L3_NO2_sensor_zenith_angle                              1327
L3_NO2_solar_azimuth_angle                              1327
L3_NO2_solar_zenith_angle                               1327
L3_NO2_stratospheric_NO2_column_number_density          1327
L3_NO2_tropopause_pressure                              1327
L3_NO2_tropospheric_NO2_column_number_density           4973
L3_O3_O3_column_number_density                           214
L3_O3_O3_effective_temperature                           214
L3_O3_cloud_fraction                                     214
L3_O3_sensor_azimuth_angle                               214
L3_O3_sensor_zenith_angle                                214
L3_O3_solar_azimuth_angle                                214
L3_O3_solar_zenith_angle                                 214
L3_CO_CO_column_number_density                          3001
L3_CO_H2O_column_number_density                         3001
L3_CO_cloud_height                                      3001
L3_CO_sensor_altitude                                   3001
L3_CO_sensor_azimuth_angle                              3001
L3_CO_sensor_zenith_angle                               3001
L3_CO_solar_azimuth_angle                               3001
L3_CO_solar_zenith_angle                                3001
L3_HCHO_HCHO_slant_column_number_density                4220
L3_HCHO_cloud_fraction                                  4220
L3_HCHO_sensor_azimuth_angle                            4220
L3_HCHO_sensor_zenith_angle                             4220
L3_HCHO_solar_azimuth_angle                             4220
L3_HCHO_solar_zenith_angle                              4220
L3_HCHO_tropospheric_HCHO_column_number_density         4220
L3_HCHO_tropospheric_HCHO_column_number_density_amf     4220
L3_CLOUD_cloud_base_height                               950
L3_CLOUD_cloud_base_pressure                             950
L3_CLOUD_cloud_fraction                                  262
L3_CLOUD_cloud_optical_depth                             950
L3_CLOUD_cloud_top_height                                950
L3_CLOUD_cloud_top_pressure                              950
L3_CLOUD_sensor_azimuth_angle                            262
L3_CLOUD_sensor_zenith_angle                             262
L3_CLOUD_solar_azimuth_angle                             262
L3_CLOUD_solar_zenith_angle                              262
L3_CLOUD_surface_albedo                                  950
L3_AER_AI_absorbing_aerosol_index                         93
L3_AER_AI_sensor_altitude                                 93
L3_AER_AI_sensor_azimuth_angle                            93
L3_AER_AI_sensor_zenith_angle                             93
L3_AER_AI_solar_azimuth_angle                             93
L3_AER_AI_solar_zenith_angle                              93
L3_SO2_SO2_column_number_density                        4173
L3_SO2_SO2_column_number_density_amf                    4173
L3_SO2_SO2_slant_column_number_density                  4173
L3_SO2_absorbing_aerosol_index                          4202
L3_SO2_cloud_fraction                                   4173
L3_SO2_sensor_azimuth_angle                             4173
L3_SO2_sensor_zenith_angle                              4173
L3_SO2_solar_azimuth_angle                              4173
L3_SO2_solar_zenith_angle                               4173
L3_CH4_CH4_column_volume_mixing_ratio_dry_air          13021
L3_CH4_aerosol_height                                  13021
L3_CH4_aerosol_optical_depth                           13021
L3_CH4_sensor_azimuth_angle                            13021
L3_CH4_sensor_zenith_angle                             13021
L3_CH4_solar_azimuth_angle                             13021
L3_CH4_solar_zenith_angle                              13021
dtype: int64

In [0]:
# for k in train[train.columns[train.columns.str.startswith('L3')]].columns:
#   train[k].fillna(train[k].mean(),inplace=True)
#   test[k].fillna(test[k].mean(),inplace=True)

In [60]:
df=train.append(test,ignore_index=True)
df.head()

        Place_ID X Date  ... L3_CH4_solar_zenith_angle
0  010Q650 X 2020-01-02  ...                 22.545118
1  010Q650 X 2020-01-03  ...                 19.293652
2  010Q650 X 2020-01-04  ...                       NaN
3  010Q650 X 2020-01-05  ...                       NaN
4  010Q650 X 2020-01-06  ...                       NaN

[5 rows x 82 columns]

In [39]:
l=['precipitable_water_entire_atmosphere','relative_humidity_2m_above_ground',
                                                        'specific_humidity_2m_above_ground','temperature_2m_above_ground','u_component_of_wind_10m_above_ground',
                                                        'v_component_of_wind_10m_above_ground']
df.sort_values('Date').groupby('Place_ID').cumsum().sort_index()

       target  ...  L3_CH4_solar_zenith_angle
0        38.0  ...                  22.545118
1        77.0  ...                  41.838770
2       101.0  ...                        NaN
3       150.0  ...                        NaN
4       171.0  ...                        NaN
...       ...  ...                        ...
46688     NaN  ...                        NaN
46689     NaN  ...                        NaN
46690     NaN  ...                        NaN
46691     NaN  ...                  66.208481
46692     NaN  ...                        NaN

[46693 rows x 79 columns]

In [38]:
l=['precipitable_water_entire_atmosphere','relative_humidity_2m_above_ground',
                                                        'specific_humidity_2m_above_ground','temperature_2m_above_ground','u_component_of_wind_10m_above_ground',
                                                        'v_component_of_wind_10m_above_ground']
df.sort_values('Place_ID').groupby('Date').cumsum().sort_index()

       target  ...  L3_CH4_solar_zenith_angle
0        38.0  ...                  22.545118
1        39.0  ...                  19.293652
2        24.0  ...                        NaN
3        49.0  ...                        NaN
4        21.0  ...                        NaN
...       ...  ...                        ...
46688     NaN  ...                        NaN
46689     NaN  ...                        NaN
46690     NaN  ...                        NaN
46691     NaN  ...                   0.000000
46692     NaN  ...                        NaN

[46693 rows x 79 columns]

In [0]:

def create_features(df, label=None,seg=None):
    """
    Creates time series features from datetime index.
    """
    df = df.copy()

    df['date'] = pd.to_datetime(df['Date'],format='%Y-%m-%d')
    df['dayofweek'] = df['date'].dt.dayofweek
    df['quarter'] = df['date'].dt.quarter
    df['month'] = df['date'].dt.month
    df['year'] = df['date'].dt.year
    df['dayofyear'] = df['date'].dt.dayofyear
    df['dayofmonth'] = df['date'].dt.day
    df['week'] = df['date'].dt.week
    df['is_month_start']=df['date'].dt.is_month_start
    df['is_month_end']=df['date'].dt.is_month_end
    df['is_quarter_start']=df['date'].dt.is_quarter_start
    df['is_quarter_end']=df['date'].dt.is_quarter_end
    df['is_year_start']=df['date'].dt.is_year_start
    df['is_year_end']=df['date'].dt.is_year_end
    df['Semester'] = np.where(df['quarter'].isin([1,2]),1,2)
    df['Date']=pd.factorize(df['Date'])[0]


    df['Place_ID']=df['Place_ID'].astype('category')

    l=['precipitable_water_entire_atmosphere','relative_humidity_2m_above_ground',
                                                        'specific_humidity_2m_above_ground','temperature_2m_above_ground','u_component_of_wind_10m_above_ground',
                                                        'v_component_of_wind_10m_above_ground']

    df[[x+'cumsum' for x in l]]=df.sort_values('Date').groupby('Place_ID').cumsum()[l].sort_index()
    df[[x+'diff' for x in l]]=df.sort_values('Date').groupby('Place_ID')[l].diff().sort_index()
    # df[[x+'cumsum_opp' for x in l]]=df.sort_values('Place_ID').groupby('Date').cumsum()[l].sort_index()
    return df.drop(['date'],axis=1)

In [0]:

d={}
for k in [x for x in df.columns if x not in ['Place_ID X Date', 'Date', 'Place_ID', 'target', 'target_min',
      'target_max', 'target_variance', 'target_count']]:
  d[k]=['min','max','sum','mean','std','median','quantile']


# t1 = df.groupby('Place_ID').agg(d)
# t1.columns=['LC_' + '_'.join(col).strip() for col in t1.columns.values]
# t1.reset_index(inplace=True)
# df = df.merge(t1,on='Place_ID',how='left')

In [0]:
t1 = df.groupby('Date').agg(d)
t1.columns=['LD_' + '_'.join(col).strip() for col in t1.columns.values]
t1.reset_index(inplace=True)
df = df.merge(t1,on='Date',how='left')

In [64]:
df=create_features(df)
df.shape

(46693, 626)

In [65]:

df_train=df[df['target'].isnull()==False].copy()
df_test=df[df['target'].isnull()==True].copy()

print(df_train.shape,df_test.shape)

(30557, 626) (16136, 626)

In [0]:
# !pip install catboost 
from lightgbm import LGBMClassifier,LGBMRegressor
from catboost import CatBoostRegressor
from sklearn.model_selection import StratifiedKFold,train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error

In [0]:
features=[x for x in df.columns if x not in ['target', 'target_count', 'target_max', 'target_min','target_variance','Place_ID']]

In [68]:
X,y=df_train[features].drop(['Place_ID X Date'],axis=1),df_train['target']
Xtest=df_test[features].drop(['Place_ID X Date'],axis=1)
bins=np.linspace(0, 1, 10) 
y_bin = np.digitize(y,bins)
y_bin


print(X.shape,Xtest.shape)
X_train,X_val,y_train,y_val = train_test_split(X,y,test_size=0.25,random_state = 1994,stratify=y_bin)

(30557, 619) (16136, 619)

In [27]:
m=CatBoostRegressor(n_estimators=7000,random_state=1994,learning_rate=0.1,eval_metric='RMSE',
               min_child_samples=12)
m.fit(X_train,y_train,eval_set=[(X_val, y_val)], early_stopping_rounds=200,verbose=400)
preds=m.predict(X_val)

0:	learn: 45.1289255	test: 46.3664605	best: 46.3664605 (0)	total: 180ms	remaining: 20m 57s
400:	learn: 21.7611191	test: 29.1906681	best: 29.1906681 (400)	total: 47.2s	remaining: 12m 56s
800:	learn: 17.2890896	test: 27.9061553	best: 27.9036234 (799)	total: 1m 34s	remaining: 12m 8s
1200:	learn: 14.4792676	test: 27.4094179	best: 27.4094179 (1200)	total: 2m 20s	remaining: 11m 19s
1600:	learn: 12.3851030	test: 27.0934823	best: 27.0934823 (1600)	total: 3m 7s	remaining: 10m 32s
2000:	learn: 10.7462410	test: 26.9058569	best: 26.9058569 (2000)	total: 3m 57s	remaining: 9m 53s
2400:	learn: 9.3953309	test: 26.7553799	best: 26.7552458 (2399)	total: 4m 44s	remaining: 9m 5s
2800:	learn: 8.3127030	test: 26.6488916	best: 26.6488916 (2800)	total: 5m 31s	remaining: 8m 16s
3200:	learn: 7.4122075	test: 26.5693553	best: 26.5675253 (3174)	total: 6m 17s	remaining: 7m 28s
3600:	learn: 6.6271534	test: 26.5280456	best: 26.5275117 (3586)	total: 7m 4s	remaining: 6m 40s
4000:	learn: 5.9492306	test: 26.4840323	best: 26.4836791 (3989)	total: 7m 51s	remaining: 5m 53s
4400:	learn: 5.3651935	test: 26.4348245	best: 26.4345185 (4390)	total: 8m 37s	remaining: 5m 5s
4800:	learn: 4.8460372	test: 26.4105385	best: 26.4085424 (4774)	total: 9m 24s	remaining: 4m 18s
5200:	learn: 4.3782660	test: 26.3898402	best: 26.3898402 (5200)	total: 10m 11s	remaining: 3m 31s
5600:	learn: 3.9760165	test: 26.3737006	best: 26.3736974 (5595)	total: 10m 58s	remaining: 2m 44s
6000:	learn: 3.6182895	test: 26.3517015	best: 26.3508228 (5985)	total: 11m 45s	remaining: 1m 57s
6400:	learn: 3.3022532	test: 26.3296888	best: 26.3296888 (6400)	total: 12m 31s	remaining: 1m 10s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 26.32638986
bestIteration = 6459

Shrink model to first 6460 iterations.

In [0]:
# m=CatBoostRegressor(n_estimators=7000,random_state=1994,learning_rate=0.1,eval_metric='RMSE',
#                min_child_samples=12)
# m.fit(X_train,y_train,eval_set=[(X_val, y_val)], early_stopping_rounds=200,verbose=400)
# preds=m.predict(X_val)

In [0]:
# m=CatBoostRegressor(n_estimators=3000,random_state=1994,learning_rate=0.1,eval_metric='RMSE',
#                min_child_samples=12)
# m.fit(X_train,y_train,eval_set=[(X_val, y_val)], early_stopping_rounds=200,verbose=500)
# preds=m.predict(X_val)

In [28]:
print("err: ",np.sqrt(mean_squared_error(y_val,preds)))

err:  26.326389863105867

In [0]:
y_pred = m.predict(Xtest,ntree_end=m.best_iteration_)

In [36]:
s['target']=y_pred
s

            Place_ID X Date     target
0      0OS9LVX X 2020-01-02  62.830435
1      0OS9LVX X 2020-01-03  36.609423
2      0OS9LVX X 2020-01-04  34.970076
3      0OS9LVX X 2020-01-05  37.238352
4      0OS9LVX X 2020-01-06  27.211318
...                     ...        ...
16131  ZZDJZMS X 2020-03-31  44.706253
16132  ZZDJZMS X 2020-04-01  50.911680
16133  ZZDJZMS X 2020-04-02  50.425744
16134  ZZDJZMS X 2020-04-03  44.299189
16135  ZZDJZMS X 2020-04-04  35.335350

[16136 rows x 2 columns]

In [37]:
s.describe()

             target
count  16136.000000
mean      57.550723
std       35.518221
min      -19.186436
25%       31.840663
50%       49.993798
75%       74.855838
max      287.624593

In [0]:
s.to_csv('colab_cb_try1.csv',index=False)

In [69]:
y_bin = pd.qcut(y,10,labels=False,duplicates='drop')
print(y_bin)

0        3
1        4
2        2
3        4
4        1
        ..
30552    1
30553    5
30554    7
30555    8
30556    7
Name: target, Length: 30557, dtype: int64

In [70]:
# s.target.describe()
err=[]
y_pred_tot=[]
from sklearn.model_selection import KFold,StratifiedKFold
fold=StratifiedKFold(n_splits=5,shuffle=True,random_state=1994)
i=1
for train_index, test_index in fold.split(X,y_bin):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    m=CatBoostRegressor(n_estimators=10000,random_state=1994,learning_rate=0.1,min_child_samples=12,eval_metric='RMSE')
    m.fit(X_train,y_train,eval_set=[(X_test, y_test)], early_stopping_rounds=200,verbose=400)
    preds=m.predict(X_test)
    print("err: ",np.sqrt(mean_squared_error(y_test,preds)))
    err.append(np.sqrt(mean_squared_error(y_test,preds)))
    p = m.predict(Xtest)
    i=i+1
    y_pred_tot.append(p)

0:	learn: 45.1793944	test: 46.6850293	best: 46.6850293 (0)	total: 136ms	remaining: 22m 44s
400:	learn: 21.6314639	test: 29.3392110	best: 29.3392110 (400)	total: 52.8s	remaining: 21m 4s
800:	learn: 17.1772581	test: 28.0276810	best: 28.0276810 (800)	total: 1m 45s	remaining: 20m 7s
1200:	learn: 14.3297971	test: 27.4262556	best: 27.4262556 (1200)	total: 2m 36s	remaining: 19m 9s
1600:	learn: 12.2580809	test: 27.0920581	best: 27.0917925 (1598)	total: 3m 29s	remaining: 18m 16s
2000:	learn: 10.5847003	test: 26.8666873	best: 26.8666873 (2000)	total: 4m 21s	remaining: 17m 25s
2400:	learn: 9.2718050	test: 26.7277620	best: 26.7267386 (2397)	total: 5m 13s	remaining: 16m 32s
2800:	learn: 8.1805019	test: 26.6252982	best: 26.6252982 (2800)	total: 6m 5s	remaining: 15m 40s
3200:	learn: 7.2187966	test: 26.5618320	best: 26.5612238 (3198)	total: 7m 1s	remaining: 14m 54s
3600:	learn: 6.4334017	test: 26.4762770	best: 26.4762770 (3600)	total: 7m 53s	remaining: 14m 1s
4000:	learn: 5.7449597	test: 26.4423736	best: 26.4423736 (4000)	total: 8m 45s	remaining: 13m 7s
4400:	learn: 5.1602059	test: 26.4092203	best: 26.4090895 (4399)	total: 9m 37s	remaining: 12m 14s
4800:	learn: 4.6446723	test: 26.3750840	best: 26.3725680 (4789)	total: 10m 29s	remaining: 11m 21s
5200:	learn: 4.1971178	test: 26.3530589	best: 26.3521329 (5192)	total: 11m 21s	remaining: 10m 28s
5600:	learn: 3.8092088	test: 26.3320495	best: 26.3319740 (5597)	total: 12m 13s	remaining: 9m 35s
6000:	learn: 3.4485540	test: 26.3136055	best: 26.3135532 (5999)	total: 13m 5s	remaining: 8m 43s
6400:	learn: 3.1391497	test: 26.3021628	best: 26.3021401 (6380)	total: 13m 57s	remaining: 7m 50s
6800:	learn: 2.8597078	test: 26.2834181	best: 26.2820315 (6778)	total: 14m 49s	remaining: 6m 58s
7200:	learn: 2.6001612	test: 26.2706180	best: 26.2702972 (7197)	total: 15m 41s	remaining: 6m 5s
7600:	learn: 2.3696910	test: 26.2575545	best: 26.2574978 (7593)	total: 16m 41s	remaining: 5m 16s
8000:	learn: 2.1647973	test: 26.2513521	best: 26.2513521 (8000)	total: 17m 33s	remaining: 4m 23s
8400:	learn: 1.9797744	test: 26.2433314	best: 26.2433314 (8400)	total: 18m 25s	remaining: 3m 30s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 26.24300843
bestIteration = 8401

Shrink model to first 8402 iterations.
err:  26.2430084347888
0:	learn: 45.4629401	test: 45.7934960	best: 45.7934960 (0)	total: 126ms	remaining: 20m 57s
400:	learn: 21.5574477	test: 27.8773599	best: 27.8773599 (400)	total: 52.1s	remaining: 20m 47s
800:	learn: 17.0945074	test: 26.3757445	best: 26.3757445 (800)	total: 1m 43s	remaining: 19m 51s
1200:	learn: 14.2876415	test: 25.7687715	best: 25.7656750 (1194)	total: 2m 35s	remaining: 18m 56s
1600:	learn: 12.1975831	test: 25.3660450	best: 25.3660450 (1600)	total: 3m 26s	remaining: 18m 4s
2000:	learn: 10.5642268	test: 25.1448793	best: 25.1446513 (1999)	total: 4m 18s	remaining: 17m 13s
2400:	learn: 9.2572871	test: 24.9781018	best: 24.9781018 (2400)	total: 5m 9s	remaining: 16m 21s
2800:	learn: 8.1602804	test: 24.8562089	best: 24.8556445 (2796)	total: 6m 1s	remaining: 15m 29s
3200:	learn: 7.2097911	test: 24.7351678	best: 24.7351678 (3200)	total: 6m 53s	remaining: 14m 38s
3600:	learn: 6.4152062	test: 24.6540593	best: 24.6540593 (3600)	total: 7m 47s	remaining: 13m 51s
4000:	learn: 5.7309364	test: 24.6026367	best: 24.6026367 (4000)	total: 8m 39s	remaining: 12m 59s
4400:	learn: 5.1396237	test: 24.5680627	best: 24.5680627 (4400)	total: 9m 33s	remaining: 12m 9s
4800:	learn: 4.6320646	test: 24.5210031	best: 24.5205877 (4791)	total: 10m 25s	remaining: 11m 17s
5200:	learn: 4.1775569	test: 24.4962516	best: 24.4955934 (5188)	total: 11m 17s	remaining: 10m 25s
5600:	learn: 3.7836431	test: 24.4636282	best: 24.4636282 (5600)	total: 12m 9s	remaining: 9m 32s
6000:	learn: 3.4243895	test: 24.4533844	best: 24.4533844 (6000)	total: 13m 1s	remaining: 8m 40s
6400:	learn: 3.1086007	test: 24.4403252	best: 24.4400215 (6392)	total: 13m 52s	remaining: 7m 48s
6800:	learn: 2.8233467	test: 24.4248650	best: 24.4247012 (6792)	total: 14m 45s	remaining: 6m 56s
7200:	learn: 2.5733447	test: 24.4151877	best: 24.4146227 (7197)	total: 15m 37s	remaining: 6m 4s
7600:	learn: 2.3492924	test: 24.4045797	best: 24.4045797 (7600)	total: 16m 34s	remaining: 5m 13s
8000:	learn: 2.1473632	test: 24.3932432	best: 24.3931017 (7990)	total: 17m 26s	remaining: 4m 21s
8400:	learn: 1.9626530	test: 24.3856959	best: 24.3854933 (8383)	total: 18m 22s	remaining: 3m 29s
8800:	learn: 1.7916223	test: 24.3760505	best: 24.3758660 (8792)	total: 19m 14s	remaining: 2m 37s
9200:	learn: 1.6369873	test: 24.3714213	best: 24.3712487 (9173)	total: 20m 6s	remaining: 1m 44s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 24.37098466
bestIteration = 9248

Shrink model to first 9249 iterations.
err:  24.370984654332865
0:	learn: 45.4820682	test: 45.3055546	best: 45.3055546 (0)	total: 136ms	remaining: 22m 43s
400:	learn: 21.7485241	test: 27.2408391	best: 27.2408391 (400)	total: 52.4s	remaining: 20m 55s
800:	learn: 17.1884859	test: 25.8570953	best: 25.8570953 (800)	total: 1m 44s	remaining: 19m 56s
1200:	learn: 14.3313081	test: 25.2947824	best: 25.2942460 (1199)	total: 2m 35s	remaining: 19m 1s
1600:	learn: 12.2031071	test: 24.9577458	best: 24.9577458 (1600)	total: 3m 27s	remaining: 18m 10s
2000:	learn: 10.5720354	test: 24.7473119	best: 24.7473119 (2000)	total: 4m 19s	remaining: 17m 18s
2400:	learn: 9.2365661	test: 24.6232820	best: 24.6232820 (2400)	total: 5m 12s	remaining: 16m 27s
2800:	learn: 8.1065568	test: 24.5382657	best: 24.5377987 (2798)	total: 6m 4s	remaining: 15m 36s
3200:	learn: 7.1842652	test: 24.4767819	best: 24.4758080 (3198)	total: 6m 56s	remaining: 14m 43s
3600:	learn: 6.3869976	test: 24.4041129	best: 24.4038466 (3597)	total: 7m 50s	remaining: 13m 56s
4000:	learn: 5.6915418	test: 24.3648816	best: 24.3646836 (3999)	total: 8m 43s	remaining: 13m 4s
4400:	learn: 5.0979464	test: 24.3346462	best: 24.3346462 (4400)	total: 9m 35s	remaining: 12m 11s
4800:	learn: 4.5769000	test: 24.3102829	best: 24.3094493 (4766)	total: 10m 27s	remaining: 11m 19s
5200:	learn: 4.1131099	test: 24.2863392	best: 24.2855878 (5196)	total: 11m 19s	remaining: 10m 27s
5600:	learn: 3.7113788	test: 24.2743145	best: 24.2733185 (5513)	total: 12m 11s	remaining: 9m 34s
6000:	learn: 3.3643696	test: 24.2559742	best: 24.2552477 (5978)	total: 13m 3s	remaining: 8m 42s
6400:	learn: 3.0565416	test: 24.2456302	best: 24.2456302 (6400)	total: 13m 55s	remaining: 7m 49s
6800:	learn: 2.7803936	test: 24.2441019	best: 24.2428780 (6644)	total: 14m 47s	remaining: 6m 57s
7200:	learn: 2.5325382	test: 24.2384103	best: 24.2381291 (7198)	total: 15m 40s	remaining: 6m 5s
7600:	learn: 2.3035714	test: 24.2326288	best: 24.2322939 (7597)	total: 16m 37s	remaining: 5m 14s
8000:	learn: 2.0930018	test: 24.2265777	best: 24.2264233 (7996)	total: 17m 32s	remaining: 4m 23s
8400:	learn: 1.9070800	test: 24.2207276	best: 24.2205046 (8390)	total: 18m 25s	remaining: 3m 30s
8800:	learn: 1.7409518	test: 24.2133562	best: 24.2130244 (8794)	total: 19m 18s	remaining: 2m 37s
9200:	learn: 1.5905984	test: 24.2073319	best: 24.2073319 (9200)	total: 20m 11s	remaining: 1m 45s
9600:	learn: 1.4566789	test: 24.2077335	best: 24.2055722 (9439)	total: 21m 3s	remaining: 52.5s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 24.20557222
bestIteration = 9439

Shrink model to first 9440 iterations.
err:  24.20557222470007
0:	learn: 45.4659465	test: 45.3156238	best: 45.3156238 (0)	total: 136ms	remaining: 22m 36s
400:	learn: 21.8422888	test: 26.9684772	best: 26.9684772 (400)	total: 52.6s	remaining: 20m 59s
800:	learn: 17.3386812	test: 25.6130184	best: 25.6123690 (799)	total: 1m 44s	remaining: 20m 2s
1200:	learn: 14.4155678	test: 24.9262086	best: 24.9262086 (1200)	total: 2m 36s	remaining: 19m 9s
1600:	learn: 12.3091017	test: 24.5375767	best: 24.5375767 (1600)	total: 3m 29s	remaining: 18m 16s
2000:	learn: 10.6925167	test: 24.3053867	best: 24.3050567 (1998)	total: 4m 21s	remaining: 17m 23s
2400:	learn: 9.3590194	test: 24.1535164	best: 24.1535164 (2400)	total: 5m 13s	remaining: 16m 31s
2800:	learn: 8.2564159	test: 24.0423080	best: 24.0410882 (2795)	total: 6m 5s	remaining: 15m 39s
3200:	learn: 7.3262730	test: 23.9564807	best: 23.9561708 (3199)	total: 7m 1s	remaining: 14m 56s
3600:	learn: 6.5238150	test: 23.9151619	best: 23.9151619 (3600)	total: 7m 54s	remaining: 14m 2s
4000:	learn: 5.8374976	test: 23.8562237	best: 23.8551174 (3975)	total: 8m 46s	remaining: 13m 9s
4400:	learn: 5.2458663	test: 23.8252801	best: 23.8249660 (4388)	total: 9m 38s	remaining: 12m 15s
4800:	learn: 4.7147230	test: 23.7931994	best: 23.7930393 (4799)	total: 10m 30s	remaining: 11m 22s
5200:	learn: 4.2520345	test: 23.7666275	best: 23.7664212 (5199)	total: 11m 22s	remaining: 10m 29s
5600:	learn: 3.8479532	test: 23.7431550	best: 23.7431550 (5600)	total: 12m 14s	remaining: 9m 36s
6000:	learn: 3.4740379	test: 23.7287265	best: 23.7282171 (5993)	total: 13m 6s	remaining: 8m 43s
6400:	learn: 3.1621933	test: 23.7120633	best: 23.7109336 (6390)	total: 13m 58s	remaining: 7m 51s
6800:	learn: 2.8799474	test: 23.7051264	best: 23.7041599 (6765)	total: 14m 50s	remaining: 6m 59s
7200:	learn: 2.6277641	test: 23.6913036	best: 23.6913036 (7200)	total: 15m 42s	remaining: 6m 6s
7600:	learn: 2.3972573	test: 23.6845624	best: 23.6837752 (7583)	total: 16m 41s	remaining: 5m 16s
8000:	learn: 2.1869236	test: 23.6767109	best: 23.6765760 (7999)	total: 17m 33s	remaining: 4m 23s
8400:	learn: 1.9988759	test: 23.6686115	best: 23.6685258 (8395)	total: 18m 25s	remaining: 3m 30s
8800:	learn: 1.8274812	test: 23.6649537	best: 23.6634719 (8771)	total: 19m 17s	remaining: 2m 37s
9200:	learn: 1.6760688	test: 23.6590808	best: 23.6584393 (9170)	total: 20m 9s	remaining: 1m 45s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 23.65843932
bestIteration = 9170

Shrink model to first 9171 iterations.
err:  23.658439322998877
0:	learn: 45.8191377	test: 44.3608345	best: 44.3608345 (0)	total: 129ms	remaining: 21m 31s
400:	learn: 21.8785661	test: 26.0614625	best: 26.0614625 (400)	total: 52.2s	remaining: 20m 48s
800:	learn: 17.3411121	test: 24.4941454	best: 24.4941454 (800)	total: 1m 43s	remaining: 19m 54s
1200:	learn: 14.4272980	test: 23.7639847	best: 23.7639847 (1200)	total: 2m 35s	remaining: 19m 1s
1600:	learn: 12.3351501	test: 23.3611568	best: 23.3593590 (1592)	total: 3m 27s	remaining: 18m 8s
2000:	learn: 10.6789649	test: 23.1033206	best: 23.1033206 (2000)	total: 4m 19s	remaining: 17m 18s
2400:	learn: 9.3260403	test: 22.9064796	best: 22.9016764 (2369)	total: 5m 12s	remaining: 16m 28s
2800:	learn: 8.2134564	test: 22.7749686	best: 22.7711737 (2783)	total: 6m 4s	remaining: 15m 36s
3200:	learn: 7.2782587	test: 22.6958153	best: 22.6958153 (3200)	total: 6m 59s	remaining: 14m 50s
3600:	learn: 6.4663689	test: 22.6244739	best: 22.6244739 (3600)	total: 7m 51s	remaining: 13m 58s
4000:	learn: 5.7817454	test: 22.5768697	best: 22.5768697 (4000)	total: 8m 44s	remaining: 13m 6s
4400:	learn: 5.1861537	test: 22.5405645	best: 22.5405645 (4400)	total: 9m 36s	remaining: 12m 13s
4800:	learn: 4.6768199	test: 22.5172439	best: 22.5172439 (4800)	total: 10m 28s	remaining: 11m 20s
5200:	learn: 4.2087053	test: 22.4856701	best: 22.4848598 (5188)	total: 11m 20s	remaining: 10m 28s
5600:	learn: 3.8130481	test: 22.4616047	best: 22.4616047 (5600)	total: 12m 12s	remaining: 9m 35s
6000:	learn: 3.4629415	test: 22.4510047	best: 22.4508875 (5999)	total: 13m 5s	remaining: 8m 43s
6400:	learn: 3.1392128	test: 22.4375975	best: 22.4374236 (6399)	total: 13m 57s	remaining: 7m 50s
6800:	learn: 2.8584446	test: 22.4226895	best: 22.4213715 (6790)	total: 14m 49s	remaining: 6m 58s
7200:	learn: 2.6037833	test: 22.4136359	best: 22.4129959 (7191)	total: 15m 42s	remaining: 6m 6s
7600:	learn: 2.3752589	test: 22.4095549	best: 22.4082562 (7555)	total: 16m 43s	remaining: 5m 16s
8000:	learn: 2.1680622	test: 22.4033138	best: 22.4026500 (7980)	total: 17m 35s	remaining: 4m 23s
8400:	learn: 1.9802281	test: 22.3979792	best: 22.3975104 (8390)	total: 18m 27s	remaining: 3m 30s
8800:	learn: 1.8111852	test: 22.3938029	best: 22.3932065 (8735)	total: 19m 19s	remaining: 2m 38s
9200:	learn: 1.6575642	test: 22.3880449	best: 22.3871624 (9174)	total: 20m 12s	remaining: 1m 45s
9600:	learn: 1.5225214	test: 22.3856921	best: 22.3842181 (9531)	total: 21m 4s	remaining: 52.5s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 22.38421813
bestIteration = 9531

Shrink model to first 9532 iterations.
err:  22.38421812511745

In [0]:
# # s.target.describe()
# err=[]
# y_pred_tot=[]
# from sklearn.model_selection import KFold,StratifiedKFold
# fold=StratifiedKFold(n_splits=5,shuffle=True,random_state=1994)
# i=1
# for train_index, test_index in fold.split(X,y_bin):
#     X_train, X_test = X.iloc[train_index], X.iloc[test_index]
#     y_train, y_test = y[train_index], y[test_index]
#     m=CatBoostRegressor(n_estimators=10000,random_state=1994,learning_rate=0.1,min_child_samples=12,eval_metric='RMSE')
#     m.fit(X_train,y_train,eval_set=[(X_test, y_test)], early_stopping_rounds=200,verbose=400)
#     preds=m.predict(X_test)
#     print("err: ",np.sqrt(mean_squared_error(y_test,preds)))
#     err.append(np.sqrt(mean_squared_error(y_test,preds)))
#     p = m.predict(Xtest)
#     i=i+1
#     y_pred_tot.append(p)

In [71]:
np.mean(err)

24.17244455238761

In [55]:
np.mean(err)

25.989198949873604

In [72]:
s['target']=np.mean(y_pred_tot,0)
s

            Place_ID X Date     target
0      0OS9LVX X 2020-01-02  47.012617
1      0OS9LVX X 2020-01-03  25.520583
2      0OS9LVX X 2020-01-04  24.068271
3      0OS9LVX X 2020-01-05  30.754561
4      0OS9LVX X 2020-01-06  30.200839
...                     ...        ...
16131  ZZDJZMS X 2020-03-31  31.170034
16132  ZZDJZMS X 2020-04-01  43.082786
16133  ZZDJZMS X 2020-04-02  44.243575
16134  ZZDJZMS X 2020-04-03  34.618446
16135  ZZDJZMS X 2020-04-04  35.395077

[16136 rows x 2 columns]

In [73]:
s.target.describe()

count    16136.000000
mean        57.319255
std         35.626605
min        -11.439729
25%         31.308458
50%         49.346583
75%         74.234379
max        289.759578
Name: target, dtype: float64

In [0]:
s.to_csv('colab_cbfolds5_try6.csv',index=False)

In [0]:
from google.colab import files
files.download('colab_cbfolds5_try6.csv')